name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main  
  push:
    branches:
      - main
      - 'releases/*'        

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
