# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Register Nuget Registry
      run: dotnet nuget add source --username ${{github.repository_owner}} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository }}/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack ppsspp-api.csproj --configuration Release
    - name: Publish
      run: dotnet nuget push "bin/Release/ppsspp-api.0.0.1.nupkg" --api-key ${{secrets.YOUR_GITHUB_PAT}} --source "github" --skip-duplicate
