name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      - name: publish nuget package
        uses: dansiegel/publish-nuget@v1.2
        with:
          filename: '*.nupkg'
          apiKey: ${{secrets.GITHUB_TOKEN}}
          feedUrl: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json   
